apiVersion: batch/v1
kind: Job
metadata:
  name: preferred-replica-election
  namespace: kafka
spec:
  template:
    metadata:
      name: preferred-replica-election
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:latest@sha256:bc6aa2962c772733a07ed9ccbc48c8b218f8c42889c83e251665d193015a2a2f
        command:
        - ./bin/kafka-preferred-replica-election.sh
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
  backoffLimit: 3
