apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
      - name: broker
        image: solsson/kafka:2.4.1-kafka-server-start@sha256:efeb80cbe35d7a39fd5d20fe93f201d3562f9914ac67afe594fe9720d21e58fa
        args:
        - /etc/kafka/server.properties.$(POD_NAME)
